name: Run CPU Pytests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  run-cpu-pytests:
    name: Run CPU Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run CPU-specific Pytests
      run: pytest toto/test -m "not cuda"
