name: Run CUDA Pytests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  run-cuda-pytests:
    name: Run CUDA Tests
    runs-on: APM-4-CORE-GPU-LINUX
    steps:
    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r toto/requirements.txt

    - name: Verify GPU Availability
      run: |
        python -c "import torch; assert torch.cuda.is_available(), 'CUDA GPU not available'"

    - name: Run CUDA-specific Pytests
      run: pytest toto/test -m cuda
